// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzsezrnkwcofobvsezgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6c2V6cm5rd2NvZm9idnNlemdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzcxNjUsImV4cCI6MjA2ODQ1MzE2NX0.D7hfhMV-4RjHyP8iBMb1GSW4pF2GjtHZV4wJmdI4_xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});